theme: jekyll-theme-minimal
title: Mini√±o Abogados 
description: Page with all of our personal!

layout: page
title: "Employees"
permalink: /mininoEmployees

layout: post
title: "Employee-Post"
date: 2025-01-31 17:30:00 -0000
categories: CATEGORY-Employee CATEGORY-Post
